// src/components/PlayRoom/PokerCard.vue
<template>
  <div class="poker-card" @click="onClick" :class="{ active, 'turn-of': turnOf }">
    <div class="left">{{ number }}</div>
    <div class="center">{{ number }}</div>
    <div class="right">{{ number }}</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'PokerCard',
  props: {
    number: {
      type: Number,
      default: 0,
    },
    turnOf: {
      type: Boolean,
      default: false,
    },
    active: {
      type: Boolean,
      default: false,
    },
  },
  setup(props, { emit }) {
    const onClick = (e: MouseEvent) => {
      e.preventDefault();
      emit('click', e);
    };

    return {
      onClick,
    };
  },
  emits: ['click'],
});
</script>

<style scoped lang="scss">
@use '~@/assets/scss/res/rem.scss';
@use '~@/assets/scss/res/colors.scss';

.poker-card {
  width: rem.rem-calc(65px);
  height: rem.rem-calc(120px);
  background: #4b00ff;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  color: colors.$white;
  cursor: pointer;
  border-radius: 8px;
  border: 1px solid #ffffff;
  padding: 0.2rem 0.4rem;

  .left {
    text-align: left;
    width: 100%;
    color: #fff;
    padding-bottom: 5px;
  }

  .center {
    text-align: center;
    width: 100%;
    color: #fff;
    border: 1px solid #fff;
    border-radius: 8px;
    padding: 1rem 0;
  }

  .right {
    text-align: right;
    width: 100%;
    color: #fff;
    padding-bottom: 5px;
  }

  &.active {
    transform: translateY(-0.5rem);
    -webkit-animation: rotateCard 0.5s linear;
    -moz-animation: rotateCard 0.5s linear;
    -o-animation: rotateCard 0.5s linear;
    animation: rotateCard 0.5s linear;
  }

  &.turn-of {
    background: darken(colors.$alto-gray, 20);
  }

  &:hover {
    background: lighten(colors.$primary, 10);
  }

  @-webkit-keyframes rotateCard {
    0% {
      transform: rotateY(0deg);
    }
    100% {
      transform: rotateY(360deg);
    }
  }
  @-moz-keyframes rotateCard {
    0% {
      transform: rotateY(0deg);
    }
    100% {
      transform: rotateY(360deg);
    }
  }
  @-o-keyframes rotateCard {
    0% {
      transform: rotateY(0deg);
    }
    100% {
      transform: rotateY(360deg);
    }
  }
  @keyframes rotateCard {
    0% {
      transform: rotateY(0deg);
    }
    100% {
      transform: rotateY(360deg);
    }
  }
}
</style>

// src/lib/components/game/PokerCard.svelte
<script lang="ts">
  interface Props {
    value: string | number;
    selected?: boolean;
    revealed?: boolean;
    faceDown?: boolean;
    onclick?: () => void;
  }

  let { value, selected = false, revealed = false, faceDown = false, onclick }: Props = $props();
</script>

<button
  class="poker-card"
  class:selected
  class:revealed
  class:face-down={faceDown}
  {onclick}
>
  <div class="card-inner">
    <div class="card-front">
      <span class="card-value">{value}</span>
    </div>
    <div class="card-back">
      <div class="card-pattern"></div>
    </div>
  </div>
</button>

<style>
  .poker-card {
    perspective: 600px;
    width: 64px;
    height: 88px;
    border: none;
    background: none;
    cursor: pointer;
    padding: 0;
    transition: transform 0.15s ease;
  }

  .poker-card:hover {
    transform: translateY(-4px);
  }

  .poker-card.selected {
    transform: translateY(-8px);
  }

  .card-inner {
    position: relative;
    width: 100%;
    height: 100%;
    transition: transform 0.5s ease;
    transform-style: preserve-3d;
  }

  .poker-card.face-down .card-inner {
    transform: rotateY(180deg);
  }

  .poker-card.revealed .card-inner {
    transform: rotateY(0deg);
  }

  .card-front,
  .card-back {
    position: absolute;
    inset: 0;
    backface-visibility: hidden;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .card-front {
    background: var(--color-surface);
    border: 2px solid var(--color-border);
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .poker-card.selected .card-front {
    border-color: var(--color-primary);
    background: var(--color-primary-light);
    box-shadow: 0 4px 12px var(--color-primary-ring);
  }

  .card-value {
    font-size: 1.25rem;
    font-weight: 700;
    color: var(--color-text);
  }

  .poker-card.selected .card-value {
    color: var(--color-primary);
  }

  .card-back {
    background: var(--color-primary);
    transform: rotateY(180deg);
    overflow: hidden;
  }

  .card-pattern {
    width: 80%;
    height: 80%;
    border-radius: 6px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    background: repeating-linear-gradient(
      45deg,
      transparent,
      transparent 4px,
      rgba(255, 255, 255, 0.08) 4px,
      rgba(255, 255, 255, 0.08) 8px
    );
  }
</style>
